version: '2.0'
services:
  web:
    build: .
    ports:
    - "3010:3010"
    environment:
      - NODE_ENV=development
    volumes:
    - .:/code
    links:
    - mongodb
  mongodb:
    image: mongo:4.2
    command: --quiet
    ports:
      - 27025:27017
